The Basics

In [19]:
import numpy as np

In [40]:
array = np.array([1,2,3,5], dtype = 'int32')

In [19]:
array

array([1, 2, 3, 5])

In [11]:
float_array = np.array([[1.2,3.5,5.6],[9.8,8.5,6.4]], dtype = 'float32')

In [12]:
float_array

array([[1.2, 3.5, 5.6],
       [9.8, 8.5, 6.4]], dtype=float32)

In [13]:
#Get Dimensions

In [14]:
#array.ndim
float_array.ndim

2

In [15]:
# Shows number of elements in each axis
float_array.shape

(2, 3)

In [16]:
#Get Size (Elements in the array)
float_array.size

6

In [17]:
#Get Type
float_array.dtype

dtype('float32')

In [18]:
#Get ItemSize
float_array.itemsize

4

Access / Change specific elements, rows and columns

In [20]:
new_array = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [21]:
print (new_array)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [23]:
#Access specific element

new_array[0,5]

6

In [24]:
#Get all elements of specific column (For example : 4th column)
new_array[:,3]

array([ 4, 11])

In [26]:
#Getting certain elements from array [startindex:endindex:stepsize]
new_array[0,2:5:2]

array([3, 5])

In [28]:
#Setting new value for particular element.

new_array[1,2]=30

In [29]:
new_array

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 30, 11, 12, 13, 14]])

In [34]:
#Setting new values for particular row.

new_array[:,2]=[8,6]

In [35]:
new_array

array([[ 1,  2,  8,  4,  5,  6,  7],
       [ 8,  9,  6, 11, 12, 13, 14]])

3D Arrays

In [49]:
three_Array = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [50]:
print (three_Array)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [51]:
#Getting specific element (work outside in)

print (three_Array[:,1,:])

[[3 4]
 [7 8]]


In [52]:
#Replace elements in 3d Array

three_Array[:,1,:]=[[89,88],[77,78]]

In [53]:
three_Array

array([[[ 1,  2],
        [89, 88]],

       [[ 5,  6],
        [77, 78]]])

##### Initializing Different Types of Arrays

In [57]:
#All Zeros Matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [60]:
#All Ones Matrix
np.ones((4,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [61]:
#Any other number
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

In [63]:
# Reuse previous created array shape to create new array
np.full(new_array.shape,56)

array([[56, 56, 56, 56, 56, 56, 56],
       [56, 56, 56, 56, 56, 56, 56]])

In [64]:
np.full_like(new_array,66)

array([[66, 66, 66, 66, 66, 66, 66],
       [66, 66, 66, 66, 66, 66, 66]])

In [94]:
#Creating Decimal Random Array
np.random.rand(3,2,4)

array([[[0.62673026, 0.04276807, 0.35928292, 0.39672009],
        [0.08000945, 0.69407586, 0.59444032, 0.880821  ]],

       [[0.32917495, 0.21586491, 0.22357586, 0.18980396],
        [0.87676996, 0.20270241, 0.30790242, 0.84667312]],

       [[0.82724555, 0.55874639, 0.81595897, 0.49458351],
        [0.11647442, 0.06224598, 0.24822759, 0.02998857]]])

In [93]:
#Random Integers Numbers
np.random.randint(3,7, size=(3,4))

array([[6, 4, 5, 6],
       [6, 6, 6, 4],
       [3, 4, 3, 4]])

In [101]:
# Reuse previous created array shape to create new Random array
np.random.random_sample(new_array.shape)

array([[0.57648485, 0.87079236, 0.06820696, 0.56648899, 0.09541808,
        0.16624303, 0.94071865],
       [0.02996295, 0.93529722, 0.74357284, 0.9977953 , 0.21932665,
        0.65371012, 0.61296695]])

In [105]:
#Repeat same Array 

# Row Wise 2D Matrix,then axis = 0,
# For Colummn Wise Repeat, axis = 1 

arr = np.array([[1,2,3]])
arr1 = np.repeat(arr,3,axis=0)
print(arr1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [126]:
output_array = np.ones((5,5), dtype = 'int')

In [127]:
print (output_array)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [132]:
output_array[1:4,1:4] = 0

In [133]:
print(output_array)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [134]:
output_array[2,2] = 9

In [135]:
print(output_array)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


## Be Careful when copying Arrays!

In [142]:
a = np.array([1,2,3])
print (a)

[1 2 3]


In [139]:
# This means that Numpy refers same array 'a' with variable 'b'
b = a
print (b)

[1 2 3]


In [140]:
b [0] = 100
print (b)
print (a)

[100   2   3]
[100   2   3]


In [145]:
#This means that Numpy will create a new reference of array 'a' and refer with variable 'b'
b = a.copy()
b[0] = 100
print ("Printing Array a : ", a)
print ("Printing Array b : ", b)

Printing Array a :  [1 2 3]
Printing Array b :  [100   2   3]


## Mathematics Capabilities

In [149]:
array = np.array([1,2,3,4])
print(array)

[1 2 3 4]


In [151]:
print(array+2)

array([3, 4, 5, 6])

In [152]:
print(array-2)

[-1  0  1  2]


In [154]:
print(array*2)

[2 4 6 8]


In [155]:
print(array/2)

[0.5 1.  1.5 2. ]


In [156]:
array ** 2

array([ 1,  4,  9, 16])

In [157]:
# Take sin of all values
np.sin(array)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [158]:
# take cos of all values
np.cos(array)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

    #For more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

 ### Linear Algebra

In [163]:
# Matrix Multiplication
firstArray = np.ones((2,3))
print (firstArray)

print ()
secondArray = np.full((3,2),2)
print (secondArray)

[[1. 1. 1.]
 [1. 1. 1.]]

[[2 2]
 [2 2]
 [2 2]]


In [165]:
np.matmul(firstArray,secondArray)

array([[6., 6.],
       [6., 6.]])

In [167]:
#Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

### Statistics

In [168]:
stats_array = np.array([[1,2,3],[4,5,6]])
stats_array

array([[1, 2, 3],
       [4, 5, 6]])

In [172]:
np.min(stats_array)
#np.max(stats_array)

1

In [176]:
np.min(stats_array, axis=0)

array([1, 2, 3])

In [178]:
np.max(stats_array,axis=1)

array([3, 6])

In [177]:
np.sum(stats_array)

21

### Reorganizing Arrays

In [180]:
beforeArray = np.array([[1,2,3,4],[5,6,7,8]])
beforeArray

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [190]:
afterArray = beforeArray.reshape(2,1,4)
afterArray

array([[[1, 2, 3, 4]],

       [[5, 6, 7, 8]]])

## Vertically Stacking Matrices

In [191]:
#Vertically stacking vectors
verticalStack1 = np.array([1,2,3,4])
verticalStack2 = np.array([5,6,7,8])

In [194]:
np.stack([verticalStack1,verticalStack2,verticalStack2,verticalStack1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [196]:
# Horizontal Stacks
horStack1 = np.ones((2,3))
horStack2 = np.zeros((2,2))

In [198]:
horStack2

array([[0., 0.],
       [0., 0.]])

In [201]:
np.hstack((horStack1,horStack2))

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

## Miscellaneous

### Load Data from Config

In [209]:
filedata = np.genfromtxt('/Users/arijitsaha/Documents/DataSet.txt', delimiter=',')
filedataInt = filedata.astype('int32')
filedataInt

array([[18,  8, 19, 86, 36,  0,  2],
       [18,  8, 19, 86, 36,  0,  2],
       [18,  8, 19, 86, 36,  0,  2]], dtype=int32)

### Boolean Masking and Advanced Indexing

In [211]:
# Check which value is more than 50 in the array fetched from data from file.
filedata < 50 


array([[ True,  True,  True, False,  True,  True,  True],
       [ True,  True,  True, False,  True,  True,  True],
       [ True,  True,  True, False,  True,  True,  True]])

In [214]:
filedata[filedata > 50]

array([86., 86., 86.])

In [213]:
# Indexing with a list in NumPy
array = np.array([1,2,3,4,5,6,7,8,9])
array[[1,2,8]]

array([2, 3, 9])

In [215]:
np.any(filedata>50, axis=0)

array([False, False, False,  True, False, False, False])

In [217]:
np.all(filedata>50, axis=0)

array([False, False, False])

In [218]:
((filedata>50) & (filedata < 100))

array([[False, False, False,  True, False, False, False],
       [False, False, False,  True, False, False, False],
       [False, False, False,  True, False, False, False]])

### Sample Problem

In [233]:
sampleArray = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
sampleArray

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [234]:
sampleArray[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [238]:
sampleArray[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [248]:
sampleArray[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])